name: Rust

on: 
  push:
    branches:
    - master
    - "*"
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Telegram Notify
      uses: appleboy/telegram-action@0.0.3

